#!/usr/bin/python3

import sys
import time

import sdnotify
from rpi_hardware_pwm import HardwarePWM

# Defaults
HARD_PWM_CHAN = 0
HARD_PWM_FREQ = 40000
SLEEP_TIME = 10
OFF_TEMP = 35
ON_TEMP = 40
MAX_TEMP = 80
FAN_LOW_PCT = 40
VERBOSE = False
NOTIFY = False

running = False

def read_temp():
    with open('/sys/class/thermal/thermal_zone0/temp', 'ro') as temp_file:
        return float(temp_file.readline()) / 1000.0


def calc_fan_speed(temp: float):
    global running
    
    if temp < OFF_TEMP:
        running = False
        return 0
    if temp < ON_TEMP and not running:
        return 0
    if temp < ON_TEMP and running:
        return FAN_LOW_PCT
    elif temp > MAX_TEMP:
        running = True
        return 100
    else:
        running = True
        return int(FAN_LOW_PCT + ((temp - ON_TEMP) / (MAX_TEMP - ON_TEMP)) * (100 - FAN_LOW_PCT))


def main():
    global running
    
    print('')
    print(f'HARD_PWM_CHAN: {HARD_PWM_CHAN}')
    print(f'HARD_PWM_FREQ: {HARD_PWM_FREQ}')
    print(f'SLEEP_TIME: {SLEEP_TIME}')
    print(f'OFF_TEMP: {OFF_TEMP}')
    print(f'ON_TEMP: {ON_TEMP}')
    print(f'MAX_TEMP: {MAX_TEMP}')
    print(f'FAN_LOW_PCT: {FAN_LOW_PCT}')
    print(f'VERBOSE: {VERBOSE}')
    print(f'NOTIFY: {NOTIFY}')
    print('')

    pwm = HardwarePWM(HARD_PWM_CHAN, hz=HARD_PWM_FREQ)
    pwm.start(100)
    running = True

    if NOTIFY:
        systemd = sdnotify.SystemdNotifier()
        systemd.notify('READY=1')

    try:
        while True:
            temp = read_temp()
            speed = calc_fan_speed(temp)
            pwm.change_duty_cycle(speed)
            if VERBOSE:
                print(f'Temp: {temp:.1f}C, Speed: {speed}%')
            if NOTIFY:
                systemd.notify('WATCHDOG=1')
            time.sleep(SLEEP_TIME)
    except KeyboardInterrupt:
        pwm.stop()
        print('')
        print('Exiting on KeyboardInterrupt')
        sys.exit()

if __name__ == '__main__':
    main()
